// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	Blocks        string
	Friends       string
	Subscriptions string
	Useremails    string
}{
	Blocks:        "blocks",
	Friends:       "friends",
	Subscriptions: "subscriptions",
	Useremails:    "useremails",
}
