// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Blocks", testBlocks)
	t.Run("Friends", testFriends)
	t.Run("Subscriptions", testSubscriptions)
	t.Run("Useremails", testUseremails)
}

func TestDelete(t *testing.T) {
	t.Run("Blocks", testBlocksDelete)
	t.Run("Friends", testFriendsDelete)
	t.Run("Subscriptions", testSubscriptionsDelete)
	t.Run("Useremails", testUseremailsDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Blocks", testBlocksQueryDeleteAll)
	t.Run("Friends", testFriendsQueryDeleteAll)
	t.Run("Subscriptions", testSubscriptionsQueryDeleteAll)
	t.Run("Useremails", testUseremailsQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Blocks", testBlocksSliceDeleteAll)
	t.Run("Friends", testFriendsSliceDeleteAll)
	t.Run("Subscriptions", testSubscriptionsSliceDeleteAll)
	t.Run("Useremails", testUseremailsSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Blocks", testBlocksExists)
	t.Run("Friends", testFriendsExists)
	t.Run("Subscriptions", testSubscriptionsExists)
	t.Run("Useremails", testUseremailsExists)
}

func TestFind(t *testing.T) {
	t.Run("Blocks", testBlocksFind)
	t.Run("Friends", testFriendsFind)
	t.Run("Subscriptions", testSubscriptionsFind)
	t.Run("Useremails", testUseremailsFind)
}

func TestBind(t *testing.T) {
	t.Run("Blocks", testBlocksBind)
	t.Run("Friends", testFriendsBind)
	t.Run("Subscriptions", testSubscriptionsBind)
	t.Run("Useremails", testUseremailsBind)
}

func TestOne(t *testing.T) {
	t.Run("Blocks", testBlocksOne)
	t.Run("Friends", testFriendsOne)
	t.Run("Subscriptions", testSubscriptionsOne)
	t.Run("Useremails", testUseremailsOne)
}

func TestAll(t *testing.T) {
	t.Run("Blocks", testBlocksAll)
	t.Run("Friends", testFriendsAll)
	t.Run("Subscriptions", testSubscriptionsAll)
	t.Run("Useremails", testUseremailsAll)
}

func TestCount(t *testing.T) {
	t.Run("Blocks", testBlocksCount)
	t.Run("Friends", testFriendsCount)
	t.Run("Subscriptions", testSubscriptionsCount)
	t.Run("Useremails", testUseremailsCount)
}

func TestHooks(t *testing.T) {
	t.Run("Blocks", testBlocksHooks)
	t.Run("Friends", testFriendsHooks)
	t.Run("Subscriptions", testSubscriptionsHooks)
	t.Run("Useremails", testUseremailsHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Blocks", testBlocksInsert)
	t.Run("Blocks", testBlocksInsertWhitelist)
	t.Run("Friends", testFriendsInsert)
	t.Run("Friends", testFriendsInsertWhitelist)
	t.Run("Subscriptions", testSubscriptionsInsert)
	t.Run("Subscriptions", testSubscriptionsInsertWhitelist)
	t.Run("Useremails", testUseremailsInsert)
	t.Run("Useremails", testUseremailsInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("BlockToUseremailUsingRequestor", testBlockToOneUseremailUsingRequestor)
	t.Run("BlockToUseremailUsingTarget", testBlockToOneUseremailUsingTarget)
	t.Run("FriendToUseremailUsingFirst", testFriendToOneUseremailUsingFirst)
	t.Run("FriendToUseremailUsingSecond", testFriendToOneUseremailUsingSecond)
	t.Run("SubscriptionToUseremailUsingRequestor", testSubscriptionToOneUseremailUsingRequestor)
	t.Run("SubscriptionToUseremailUsingTarget", testSubscriptionToOneUseremailUsingTarget)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("UseremailToRequestorBlocks", testUseremailToManyRequestorBlocks)
	t.Run("UseremailToTargetBlocks", testUseremailToManyTargetBlocks)
	t.Run("UseremailToFirstFriends", testUseremailToManyFirstFriends)
	t.Run("UseremailToSecondFriends", testUseremailToManySecondFriends)
	t.Run("UseremailToRequestorSubscriptions", testUseremailToManyRequestorSubscriptions)
	t.Run("UseremailToTargetSubscriptions", testUseremailToManyTargetSubscriptions)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("BlockToUseremailUsingRequestorBlocks", testBlockToOneSetOpUseremailUsingRequestor)
	t.Run("BlockToUseremailUsingTargetBlocks", testBlockToOneSetOpUseremailUsingTarget)
	t.Run("FriendToUseremailUsingFirstFriends", testFriendToOneSetOpUseremailUsingFirst)
	t.Run("FriendToUseremailUsingSecondFriends", testFriendToOneSetOpUseremailUsingSecond)
	t.Run("SubscriptionToUseremailUsingRequestorSubscriptions", testSubscriptionToOneSetOpUseremailUsingRequestor)
	t.Run("SubscriptionToUseremailUsingTargetSubscriptions", testSubscriptionToOneSetOpUseremailUsingTarget)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("UseremailToRequestorBlocks", testUseremailToManyAddOpRequestorBlocks)
	t.Run("UseremailToTargetBlocks", testUseremailToManyAddOpTargetBlocks)
	t.Run("UseremailToFirstFriends", testUseremailToManyAddOpFirstFriends)
	t.Run("UseremailToSecondFriends", testUseremailToManyAddOpSecondFriends)
	t.Run("UseremailToRequestorSubscriptions", testUseremailToManyAddOpRequestorSubscriptions)
	t.Run("UseremailToTargetSubscriptions", testUseremailToManyAddOpTargetSubscriptions)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Blocks", testBlocksReload)
	t.Run("Friends", testFriendsReload)
	t.Run("Subscriptions", testSubscriptionsReload)
	t.Run("Useremails", testUseremailsReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Blocks", testBlocksReloadAll)
	t.Run("Friends", testFriendsReloadAll)
	t.Run("Subscriptions", testSubscriptionsReloadAll)
	t.Run("Useremails", testUseremailsReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Blocks", testBlocksSelect)
	t.Run("Friends", testFriendsSelect)
	t.Run("Subscriptions", testSubscriptionsSelect)
	t.Run("Useremails", testUseremailsSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Blocks", testBlocksUpdate)
	t.Run("Friends", testFriendsUpdate)
	t.Run("Subscriptions", testSubscriptionsUpdate)
	t.Run("Useremails", testUseremailsUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Blocks", testBlocksSliceUpdateAll)
	t.Run("Friends", testFriendsSliceUpdateAll)
	t.Run("Subscriptions", testSubscriptionsSliceUpdateAll)
	t.Run("Useremails", testUseremailsSliceUpdateAll)
}
