// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testFriends(t *testing.T) {
	t.Parallel()

	query := Friends()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testFriendsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friend{}
	if err = randomize.Struct(seed, o, friendDBTypes, true, friendColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Friends().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFriendsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friend{}
	if err = randomize.Struct(seed, o, friendDBTypes, true, friendColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Friends().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Friends().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFriendsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friend{}
	if err = randomize.Struct(seed, o, friendDBTypes, true, friendColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FriendSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Friends().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFriendsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friend{}
	if err = randomize.Struct(seed, o, friendDBTypes, true, friendColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := FriendExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Friend exists: %s", err)
	}
	if !e {
		t.Errorf("Expected FriendExists to return true, but got false.")
	}
}

func testFriendsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friend{}
	if err = randomize.Struct(seed, o, friendDBTypes, true, friendColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	friendFound, err := FindFriend(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if friendFound == nil {
		t.Error("want a record, got nil")
	}
}

func testFriendsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friend{}
	if err = randomize.Struct(seed, o, friendDBTypes, true, friendColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Friends().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testFriendsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friend{}
	if err = randomize.Struct(seed, o, friendDBTypes, true, friendColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Friends().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testFriendsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	friendOne := &Friend{}
	friendTwo := &Friend{}
	if err = randomize.Struct(seed, friendOne, friendDBTypes, false, friendColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}
	if err = randomize.Struct(seed, friendTwo, friendDBTypes, false, friendColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = friendOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = friendTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Friends().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testFriendsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	friendOne := &Friend{}
	friendTwo := &Friend{}
	if err = randomize.Struct(seed, friendOne, friendDBTypes, false, friendColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}
	if err = randomize.Struct(seed, friendTwo, friendDBTypes, false, friendColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = friendOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = friendTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Friends().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func friendBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Friend) error {
	*o = Friend{}
	return nil
}

func friendAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Friend) error {
	*o = Friend{}
	return nil
}

func friendAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Friend) error {
	*o = Friend{}
	return nil
}

func friendBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Friend) error {
	*o = Friend{}
	return nil
}

func friendAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Friend) error {
	*o = Friend{}
	return nil
}

func friendBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Friend) error {
	*o = Friend{}
	return nil
}

func friendAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Friend) error {
	*o = Friend{}
	return nil
}

func friendBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Friend) error {
	*o = Friend{}
	return nil
}

func friendAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Friend) error {
	*o = Friend{}
	return nil
}

func testFriendsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Friend{}
	o := &Friend{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, friendDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Friend object: %s", err)
	}

	AddFriendHook(boil.BeforeInsertHook, friendBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	friendBeforeInsertHooks = []FriendHook{}

	AddFriendHook(boil.AfterInsertHook, friendAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	friendAfterInsertHooks = []FriendHook{}

	AddFriendHook(boil.AfterSelectHook, friendAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	friendAfterSelectHooks = []FriendHook{}

	AddFriendHook(boil.BeforeUpdateHook, friendBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	friendBeforeUpdateHooks = []FriendHook{}

	AddFriendHook(boil.AfterUpdateHook, friendAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	friendAfterUpdateHooks = []FriendHook{}

	AddFriendHook(boil.BeforeDeleteHook, friendBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	friendBeforeDeleteHooks = []FriendHook{}

	AddFriendHook(boil.AfterDeleteHook, friendAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	friendAfterDeleteHooks = []FriendHook{}

	AddFriendHook(boil.BeforeUpsertHook, friendBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	friendBeforeUpsertHooks = []FriendHook{}

	AddFriendHook(boil.AfterUpsertHook, friendAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	friendAfterUpsertHooks = []FriendHook{}
}

func testFriendsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friend{}
	if err = randomize.Struct(seed, o, friendDBTypes, true, friendColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Friends().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFriendsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friend{}
	if err = randomize.Struct(seed, o, friendDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(friendColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Friends().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFriendToOneUseremailUsingFirst(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Friend
	var foreign Useremail

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, friendDBTypes, false, friendColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, useremailDBTypes, false, useremailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Useremail struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.FirstID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.First().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := FriendSlice{&local}
	if err = local.L.LoadFirst(ctx, tx, false, (*[]*Friend)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.First == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.First = nil
	if err = local.L.LoadFirst(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.First == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testFriendToOneUseremailUsingSecond(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Friend
	var foreign Useremail

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, friendDBTypes, false, friendColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, useremailDBTypes, false, useremailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Useremail struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.SecondID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Second().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := FriendSlice{&local}
	if err = local.L.LoadSecond(ctx, tx, false, (*[]*Friend)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Second == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Second = nil
	if err = local.L.LoadSecond(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Second == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testFriendToOneSetOpUseremailUsingFirst(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Friend
	var b, c Useremail

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, friendDBTypes, false, strmangle.SetComplement(friendPrimaryKeyColumns, friendColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, useremailDBTypes, false, strmangle.SetComplement(useremailPrimaryKeyColumns, useremailColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, useremailDBTypes, false, strmangle.SetComplement(useremailPrimaryKeyColumns, useremailColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Useremail{&b, &c} {
		err = a.SetFirst(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.First != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.FirstFriends[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.FirstID != x.ID {
			t.Error("foreign key was wrong value", a.FirstID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.FirstID))
		reflect.Indirect(reflect.ValueOf(&a.FirstID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.FirstID != x.ID {
			t.Error("foreign key was wrong value", a.FirstID, x.ID)
		}
	}
}
func testFriendToOneSetOpUseremailUsingSecond(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Friend
	var b, c Useremail

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, friendDBTypes, false, strmangle.SetComplement(friendPrimaryKeyColumns, friendColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, useremailDBTypes, false, strmangle.SetComplement(useremailPrimaryKeyColumns, useremailColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, useremailDBTypes, false, strmangle.SetComplement(useremailPrimaryKeyColumns, useremailColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Useremail{&b, &c} {
		err = a.SetSecond(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Second != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.SecondFriends[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.SecondID != x.ID {
			t.Error("foreign key was wrong value", a.SecondID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.SecondID))
		reflect.Indirect(reflect.ValueOf(&a.SecondID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.SecondID != x.ID {
			t.Error("foreign key was wrong value", a.SecondID, x.ID)
		}
	}
}

func testFriendsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friend{}
	if err = randomize.Struct(seed, o, friendDBTypes, true, friendColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFriendsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friend{}
	if err = randomize.Struct(seed, o, friendDBTypes, true, friendColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FriendSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFriendsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friend{}
	if err = randomize.Struct(seed, o, friendDBTypes, true, friendColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Friends().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	friendDBTypes = map[string]string{`ID`: `bigint`, `FirstID`: `bigint`, `SecondID`: `bigint`}
	_             = bytes.MinRead
)

func testFriendsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(friendPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(friendAllColumns) == len(friendPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Friend{}
	if err = randomize.Struct(seed, o, friendDBTypes, true, friendColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Friends().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, friendDBTypes, true, friendPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testFriendsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(friendAllColumns) == len(friendPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Friend{}
	if err = randomize.Struct(seed, o, friendDBTypes, true, friendColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Friends().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, friendDBTypes, true, friendPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(friendAllColumns, friendPrimaryKeyColumns) {
		fields = friendAllColumns
	} else {
		fields = strmangle.SetComplement(
			friendAllColumns,
			friendPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := FriendSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testFriendsUpsert(t *testing.T) {
	t.Parallel()

	if len(friendAllColumns) == len(friendPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Friend{}
	if err = randomize.Struct(seed, &o, friendDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Friend: %s", err)
	}

	count, err := Friends().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, friendDBTypes, false, friendPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Friend struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Friend: %s", err)
	}

	count, err = Friends().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
