// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Blocks", testBlocksUpsert)

	t.Run("Friends", testFriendsUpsert)

	t.Run("Subscriptions", testSubscriptionsUpsert)

	t.Run("Useremails", testUseremailsUpsert)
}
